Update clouds script
Improve errors and information messages
Add yad dialogs

Signed-off-by: Daniel Llewellyn <daniel@bowlhat.net>

diff --git a/snap/local/bin/clouds b/snap/local/bin/clouds
--- a/snap/local/bin/clouds
+++ b/snap/local/bin/clouds
@@ -14,18 +14,22 @@ echo "*** Checking for Windows Installer ISO"
 if [ ! -f "$SNAP_USER_COMMON"/windows-installer.iso ]; then
 	URL="$(node $SNAP/index.js)"
 	RV=$?
-	echo "Download URL=$URL"
+	echo "INFO: ISO download URL=$URL"
 	if [ $RV = 0 ] && [ -n "$URL" ]; then
 		wget "${URL}" -O "$SNAP_USER_COMMON"/windows-installer.iso -U "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" 2>&1 | \
 		perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading Windows ISO image... \2 (\3)/' | \
 		yad --progress --title="Windows ISO Image" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
 
-		if [ $? != 0 ]; then
-			echo "Failed to download Windows ISO image"
+		if [ $? = 0 ]; then
+			echo "INFO: ISO downloaded successfully"
+		else
+			echo "ERROR: Failed to download Windows ISO image"
+			yad --center --button=OK --title="Error" --text="Failed to download Windows ISO image"
 			exit 1
 		fi
 	else
-		echo "Failed to get download URL"
+		echo "ERROR: Failed to get Windows ISO image download URL"
+		yad --center --button=OK --title="Error" --text="Failed to get Windows ISO image download URL"
 		exit 1
 	fi
 fi
